info:
  businessSide: xjjdog
  serviceName: sale-fast-webapp
  author: xjjdog
server:
  port: 8888
  context-path: /
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: .
      pattern: "%{X-Forwarded-For}i %a %{X-B3-TraceId}i %t %m %U %s %b %D"
      rename-on-rotate: true
      suffix: .log
      prefix: access
      rotate: true
      buffered: false
      file-date-format: yyyy-MM-dd
    uri-encoding: UTF-8

spring:
  application:
    name: sale-fast-webapp
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  aop:
    proxyTargetClass: true
    auto: true
  jmx:
    enabled: true
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 10000
      #test-while-idle: true
      #validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 15000
      default-auto-commit: true
      min-evictable-idle-time-millis: 30000
      use-global-data-source-stat: true
      filter:
        stat:
          enabled: false
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2
        slf4j:
          data-source-log-enabled: true
          data-source-logger-name: DRUID
          statement-executable-sql-log-enable: true
          statement-logger-name: DRUID

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=yjmyzz
        healthCheckPath: /info.json
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


mybatis:
  mapper-locations: classpath*:sqlmap/*Mapper.xml
  type-aliases-package: ${package}.entity
  configuration:
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    lazy-loading-enabled: false
    # 使全局的映射器启用或禁用缓存
    cache-enabled: true
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    aggressive-lazy-loading: false
    # 是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    multiple-result-sets-enabled: true
    # 是否可以使用列的别名 (取决于驱动的兼容性) default:true
    use-column-label: true
    # 允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    use-generated-keys: false
    # 指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: partial
    # 这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    default-executor-type: simple
    # 使用驼峰命名法转换字段。
    map-underscore-to-camel-case: true
    # 设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    local-cache-scope: session
    # 设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: 'null'


#管理
management:
  security:
    enabled: false
  context-path: /ops


endpoints:
  shutdown:
    enabled: false
    sensitive: false
  jolokia:
    enabled: true


swagger:
  title: ${artifactId}
  contact:
    name: xjjdog
  base-package: ${package}.controller
  base-path: /**
  exclude-path: /error, /ops/**
